networks:

  baserow:

  docassemble:

  n8n:

volumes:

  baserow_data:
    external: true

  dabackup:
    external: true

  n8n_data:
    external: true

services:

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
        - TUNNEL_TOKEN=eyJhIjoiZDI1MjE2N2I1ZjUwYjdjODgzZmZhMDQ0NDZiOWJhYzMiLCJ0IjoiZDE1NTQzNDctYWNjNS00YWMzLTgyMTYtODM4NjZkNGFhNmE0IiwicyI6Ik5HRmlOVGcwWVRRdE1XTm1ZaTAwWlRVeExUa3lNVE10TVRRNE5qSTFObVZoTXpVNCJ9
    networks:
        - baserow
        - docassemble
        - n8n

  baserow:
    container_name: baserow
    image: baserow/baserow:develop-latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - baserow_data:/baserow/data
    networks:
      - baserow

  docassemble:
    image: jhpyle/docassemble:latest
    container_name: docassemble
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 6m
    ports:
      - "8082:80"
    volumes:
      - dabackup:/usr/share/docassemble/backup
    networks:
      - docassemble

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "8081:8081"
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=8081
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n

