volumes:
  n8n_storage:
  
networks:
  n8n-xps:
  
services:

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: "cf-tunnel"
    restart: unless-stopped
    command: tunnel run
    environment:
        - TUNNEL_TOKEN=eyJhIjoiZDI1MjE2N2I1ZjUwYjdjODgzZmZhMDQ0NDZiOWJhYzMiLCJ0IjoiODRiNmRhZjMtYTU3MC00Y2MyLWE1ODYtZTFjYzE5MTBlMmU3IiwicyI6IlptUXhPRFl4T1dRdE9EWmlNUzAwTjJaaExUazVZbVF0T1dVeVpqVTVOekJsTURBNCJ9
    networks:
        - n8n-xps

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    privileged: true
    environment:
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_HOST=xps.ccn8n.org
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - NODE_ENV=production
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - WEBHOOK_URL=https://xps.ccn8n.org/
      - N8N_ENCRYPTION_KEY
      - N8N_USER_MANAGEMENT_JWT_SECRET
    ports:
      - 5678:5678
    networks:
      - n8n-xps
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
